version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.3-alpine
    environment:
      POSTGRES_DB: elections_us
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app:18
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: elections_us
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
volumes:
  postgres_data:
